[package]
name = "ascii-izer"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["color"]
crossterm = ["dep:crossterm"]
color = []

[dependencies]
crossterm = { version = "0.28.1", optional = true }
image = "0.25.5"
